### PR TITLE
feat(db): added support for query logging

### PR DESCRIPTION
**Pull request by soapdog**
Adds support for database query logging for debugging purposes.

If the database configuration has ```log_database_queries = true``` then a file called ```runtime/logs/query.log``` is appended with the SQL queries issued from Sailor Models. At this point only the SQL queries are recorded, result values and location of the queries might be added in the future.

Changes were made to the ```db``` folder, the blank app and the configuration template.

### CODE REVIEW

**Comment by Etiene** [comment]
Awesome! Tests are failing on Lua 5.2 though, could you take a look at that? :)
https://travis-ci.org/sailorproject/sailor/builds/201879964

**Comment by soapdog** [comment]
@Etiene just took a quick look, apparently ```sailor.path``` is resolving to ```nil``` on Lua 5.2, will look further into it.

**Comment by Etiene** [comment]
Hello @soapdog any updates? :)

**Comment by soapdog** [comment]
@Etiene I am swamped in work this week. I will update this next week, on Monday, when I am a normal human being again. 😄

**Comment by Etiene** [comment]
closing due to inactivity

**Pull request closed without merging**
