### PR TITLE
style: remove empty lines in test/dev-app/models/

### PR DESCRIPTION
**Pull request by luisbg**
Small thing I noticed while reading dev-app

Thank you :smile:

### CODE REVIEW

**Comment by Etiene** [comment]
:dancers:

**Comment by luisbg** [comment]
:dancers: indeed hahahaa

Hopefully I will have some time tomorrow to read some internal Sailor code.

**Comment by luisbg** [comment]
Why is coveralls telling me about this now? This was merged a year ago. LOL

**Comment by CodelessFuture** [comment]
Really don't know why. It tells me too!

**Pull request merged**
