### PR TITLE
Update Lua version in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by luisbg**
To keep consistency with the version recommended in docs/INSTALL_LINUX.md

### CODE REVIEW

**Comment by Etiene** [comment]
Hm... I'm wondering if we should set the linux docs to 5.1 instead. Although sailor is compatible with both versions of Lua, depending on the webserver used, such as nginx, it will require 5.1...

**Comment by luisbg** [comment]
I could offer a patch where docs/INSTALL_LINUX.md suggests the lua5.1 debian package instead. The main issue I am trying to correct is the inconsitency, which I noticed because I am starting to play with the project with the intent of doing bigger things later on :)

Thanks for your very prompt reply

**Comment by Etiene** [comment]
Yea, maybe that would be better :)

**Comment by Etiene** [comment]
Thanks for catching this! :D

**Pull request closed without merging**
