### PR TITLE
Improve the Nginx handle of friendly URL

### PR DESCRIPTION
**Pull request by xspager**
This changes relate to the improvements I mention on the issue #72 and improve on the improvements :+1:  done to close issue #48

### CODE REVIEW

**Comment by Etiene** [comment]
Trying to solve our problems with travis first...

**Comment by Etiene** [comment]
Ok! Now some comments.

I need to test this more precisely before merging because as far as I know mime.types is necessary for openresty!

Also, will the friendly url support get variables? 
As in /controller/action/getparam1/getvalue1/getparam2/getvalue2....

We need to add some unit tests on that :)

**Comment by xspager** [comment]
I'm not familiar with openresty, every time I see Nginx packaged it comes with mime.types and it is usually put in /etc/nginx/mime.types by the package manager. The Nginx config in /etc/nginx/nginx.conf usually include most of things you have to worry about, in old systems you usually add or comment things on this file and in newer systems you just put a file with the "server {}" block in /etc/nginx/sites-available as pointed out on the file comments.

I'll try to look on the second question and install openresty to see if the file  mime.types is included.

**Comment by xspager** [comment]
Removed the changes, I'll take some time soon to create a new PR.

...btw, OpenResty really need the mime.types file :disappointed:

**Comment by Etiene** [comment]
awn :cry: thanks for the effort though! I think we just need to maybe create a separate module only for the routing, so them  we can reference to it for the friendly urls too

**Pull request closed without merging**
