### PR TITLE
Added page:json function, added dksjon dep, added unit test for page:…

### PR DESCRIPTION
**Pull request by louis77**
…json, modified docs to include page:json

This should conclude sailorproject/sailor/issues/86

### CODE REVIEW

**Comment by louis77** [comment]
OMG... let me check that.

**Comment by Etiene** [comment]
awesome! didn't you suggest to also set the theme to nil, though?

**Comment by louis77** [comment]
@Etiene As far as I understand is the whole theme-ing done in the Page:render function, which is not used by Page:json. I didn't see the need to nil the theme. Could you point me to the code where you think theme = nil would benefit?

**Comment by Etiene** [comment]
You are right! :)

Thanks for this great addition! :dancers:

**Pull request merged**
